version: '3.8'

services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/colab_challenge
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=gemini-1.5-flash
      - PORT=3000
    ports:
      - '3000:3000'

volumes:
  mongo-data:

